# Generated by Django 5.2.5 on 2026-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_booking_paid_at_booking_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_currency',
            field=models.CharField(default='ngn', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_provider',
            field=models.CharField(default='paystack', max_length=20),
        ),
    ]
